Repository open-spaced-repetition/fsrs4anki-helper, pull requests merged in 2023-08, with the labels that each got.

#181 Feat/true retention by card maturity
  config.json
  configuration.py
  stats.py
Labels: enhancement

#182 Feat/improve D graph
  stats.py
Labels: enhancement

#183 Fix/merge overdue load to today
  reschedule.py
Labels: invalid

#192 Feat/re-arrange-layout-of-the-stats
  stats.py
Labels: enhancement

#193 Fix/true retention table is empty when first enter
  stats.py
Labels: invalid

#195 Feat/retention graph
  stats.py
Labels: enhancement

#202 Fix card counts in true retention table
  stats.py
Labels: invalid

#203 Feat/reschedule card after review
  __init__.py
  config.json
  configuration.py
  schedule/__init__.py
  schedule/advance.py
  schedule/disperse_siblings.py
  schedule/postpone.py
  schedule/reschedule.py
  schedule/reset.py
  sync_hook.py
  utils.py
Labels: enhancement

#209 Fix/nid referenced before assignment
  schedule/disperse_siblings.py
Labels: bug
