Repository open-spaced-repetition/fsrs4anki-helper, pull requests merged in 2023-09, with the labels that each got.

#213 Feat/target R column in browser
  browser/browser.py
  browser/custom_columns.py
Labels: enhancement

#217 Fix/don't disperse manual rescheduled cards
  schedule/disperse_siblings.py
Labels: bug

#218 Doc/update description of average retention
  stats.py
Labels: documentation

#221 Feat/Estimated total knowledge based on notes
  stats.py
Labels: enhancement

#223 Define mature cards
  stats.py
Labels: documentation

#227 Fix/handle none in auto reschedule when review
  schedule/reschedule.py
Labels: bug

#241 Doc/change wording of feature
  __init__.py
Labels: documentation
